import '../../style/global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Jadwal Piala Dunia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className='container min-h-screen'>
          {children}
        </main>
        <footer className='p-[40px] bg-zinc-100 mt-[10px]'>
          Made By Rachmanullah
        </footer>
      </body>
    </html>
  )
}
